version: '3.8'
services:
  twigo_panel:
    build: .
    container_name: twigo_panel
    ports:
      - "80:80"
    networks:
      - twigo_panel
    depends_on:
      - postgres
    environment:
      - BEARER_TOKEN: ${BEARER_TOKEN}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_DB: ${POSTGRES_DB}
  postgres:
    image: postgres:10.20-alpine3.15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - twigo_panel

volumes:
  db:
    driver: local

networks:
  twigo_panel:
    driver: local